version: "3.1"

services:
  mongo:
    image: mongo:5.0-focal
    restart: always
    ports:
      - ${MONGO_DOMAIN}:${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_USER_PASSWORD}
